# Generated by Django 4.2.16 on 2024-10-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_alter_scrapeddata_field_name_alter_scrapeddata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='field_name',
            field=models.TextField(),
        ),
    ]
