# Generated by Django 4.2.16 on 2024-11-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterias', '0002_criterias_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterias',
            old_name='website',
            new_name='web',
        ),
    ]
