# Generated by Django 4.2.16 on 2024-11-01 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterias', '0003_rename_website_criterias_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterias',
            old_name='web',
            new_name='web_id',
        ),
    ]
