# Generated by Django 4.2.16 on 2024-11-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '__first__'),
        ('criterias', '0004_rename_web_criterias_web_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterias',
            name='web_id',
        ),
        migrations.AddField(
            model_name='criterias',
            name='web',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='websites.website'),
        ),
    ]
