# Generated by Django 4.2.16 on 2024-11-01 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '__first__'),
        ('criterias', '0006_rename_web_criterias_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterias',
            name='web_id',
            field=models.ForeignKey(blank=True, db_column='web_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='websites.website'),
        ),
    ]
