# Generated by Django 4.2.16 on 2024-11-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterias', '0007_alter_criterias_web_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterias',
            name='name',
        ),
        migrations.AddField(
            model_name='criterias',
            name='type',
            field=models.CharField(choices=[('nav', 'Navigation'), ('content', 'Content')], default='content', max_length=7),
        ),
    ]
